import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
// import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { StoreProvider } from './storeProvider';
import { HeaderPage } from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          {/* <HeaderPage /> */}
          {children}
          {/* <Footer /> */}
        </body>
      </html>
    </StoreProvider>
  );
}
